name: edu_vista
description: "Online E-Learning Application"

publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.5.0-180.3.beta <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.0.0+2
  shared_preferences: ^2.0.0
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  flutter_bloc: ^8.1.6
  cloud_firestore: ^5.2.1
  flutter_svg: ^2.0.9
  flutter_rating_bar: ^4.0.1
  firebase_storage: ^12.1.3
  file_picker: ^5.5.0
  image_cropper: ^8.0.2
  responsive_framework: ^1.5.1
  paymob_payment: ^0.0.1+1
  flutter_dotenv: ^5.1.0
  video_box:
    git:
      url: https://github.com/mahmoudelgharabawi/flutter_video_box.git
 
dependency_overrides:
  webview_flutter_android: ^3.16.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - .env

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/PlusJakartaSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 300
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600