// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXlMPfF10R79Z4EAD2nocHtjz-vHFnSZ4',
    appId: '1:993277968677:web:f15d1f91a7f899b2a79acc',
    messagingSenderId: '993277968677',
    projectId: 'edu-vista-ea480',
    authDomain: 'edu-vista-ea480.firebaseapp.com',
    storageBucket: 'edu-vista-ea480.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXlMPfF10R79Z4EAD2nocHtjz-vHFnSZ4',
    appId: '1:993277968677:android:7bd2ecd3ff71c053a79acc',
    messagingSenderId: '993277968677',
    projectId: 'edu-vista-ea480',
    storageBucket: 'edu-vista-ea480.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEfSE_ZC2J44W84KIRaLRH3CHaiR-sRso',
    appId: '1:993277968677:ios:c1089877b5060dc0a79acc',
    messagingSenderId: '993277968677',
    projectId: 'edu-vista-ea480',
    storageBucket: 'edu-vista-ea480.appspot.com',
    iosClientId: '993277968677-0mf79ts7nfv7cof4imo8lumbfs2hsepm.apps.googleusercontent.com',
    iosBundleId: 'com.example.eduVista',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEfSE_ZC2J44W84KIRaLRH3CHaiR-sRso',
    appId: '1:993277968677:ios:c1089877b5060dc0a79acc',
    messagingSenderId: '993277968677',
    projectId: 'edu-vista-ea480',
    storageBucket: 'edu-vista-ea480.appspot.com',
    iosClientId: '993277968677-0mf79ts7nfv7cof4imo8lumbfs2hsepm.apps.googleusercontent.com',
    iosBundleId: 'com.example.eduVista',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXlMPfF10R79Z4EAD2nocHtjz-vHFnSZ4',
    appId: '1:993277968677:web:1d0cc62b13e3adf2a79acc',
    messagingSenderId: '993277968677',
    projectId: 'edu-vista-ea480',
    authDomain: 'edu-vista-ea480.firebaseapp.com',
    storageBucket: 'edu-vista-ea480.appspot.com',
  );

}